/***********************************************************************/
/*                                                                     */
/*  FILE        :led_7_counter.c                                       */
/*  DATE        :Thu, Mar 15, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

int num[10]={63,6,91,79,102,109,125,39,127,111},x=0;
int i=0,s=0,t_s=0,m=0,j=0,btn_reset=0,btn_start=0,start_flag=0,reset_flag=0,read_flag=1;	


void main(void)
{
	R_PG_Clock_Set();
	R_PG_IO_PORT_Set_P7();
	R_PG_IO_PORT_Set_PB();
	R_PG_IO_PORT_Set_PA();
	
	
	while(1)
	{ 
		 R_PG_IO_PORT_Read_PA3(&btn_start);
         R_PG_IO_PORT_Read_PA2(&btn_reset);
		
	  if( ((!btn_reset) && read_flag) || ((!btn_start) && read_flag))  
			{
				read_flag=0;
				R_PG_Timer_Start_CMT_U0_C0();
			}
			
	  if(start_flag && read_flag)
	  {  
		 start_flag=0;
		 x++;
		 x=x%2;
		 if(x) 
		    R_PG_Timer_Start_CMT_U0_C1();
	     else
		    R_PG_Timer_HaltCount_CMT_U0_C1();
	 
	  }
	  
	  
	  if(reset_flag)
	  {   
	    i=0;s=0;t_s=0;m=0;
		reset_flag=0;
	  }
	  
		
	   R_PG_IO_PORT_Write_PB(num[i]);
	   R_PG_IO_PORT_Write_P7(1);
	   for(j=0;j<500;j++);
	    
	   R_PG_IO_PORT_Write_PB(num[s]+128);
	   R_PG_IO_PORT_Write_P7(2);
	   for(j=0;j<500;j++);
	 
	   R_PG_IO_PORT_Write_PB(num[t_s]);
	   R_PG_IO_PORT_Write_P7(4);
	   for(j=0;j<500;j++);
	   
	   R_PG_IO_PORT_Write_PB(num[m]);
	   R_PG_IO_PORT_Write_P7(8);
	   for(j=0;j<500;j++);

		
	}

}
void Cmt0IntFunc (void)  // 20ms CMT
{   
   R_PG_IO_PORT_Read_PA3(&btn_start);
   R_PG_IO_PORT_Read_PA2(&btn_reset);
   if( !btn_start )
             start_flag=1;
   if( !btn_reset )
             reset_flag=1;
    
	read_flag=1;
	R_PG_Timer_HaltCount_CMT_U0_C0();

}

void Cmt1IntFunc (void)  // 100ms CMT
{
	
	i++;
	if(i==10)
	{   
		i=i%10;	
		s++;
	}
	if(s==10)
	{
		s=s%10;
		t_s++;
	}
	if(t_s==10)
	{
		t_s=t_s%10;
		m++;
	}
	if(i==9 && s==9 && t_s==9 && m==9)
	
	 { i=0;s=0;t_s=0;m=0;}
}



#ifdef __cplusplus
void abort(void)
{

}
#endif
