/***********************************************************************/
/*                                                                     */
/*  FILE        :SCI_RxTx_7_test.c                                     */
/*  DATE        :Thu, Mar 29, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

char rx[1]={0};
int na[10]={12,8,12,12,8,4,0,12,12,12};
int nb[10]={57,1,88,73,97,105,121,33,121,105},i[4]={0,0,0,0},k=0,s,x=0;
int ch1_flag=0,ch2_flag=0,ch3_flag=0,ch4_flag=0,back_flag=0;

void main(void)
{
	R_PG_Clock_Set();
	R_PG_IO_PORT_Set_P7();
	R_PG_IO_PORT_Set_PB();
	R_PG_IO_PORT_Set_PA();
	
	R_PG_SCI_Set_C0();	
	R_PG_SCI_StartReceiving_C0(&rx,1);
	
	while(1)
	{
		
     if(back_flag) {
	   back_flag=0;
	   k=0;
	   for(s=0;s<3;s++)
	      { i[s]=i[s+1]; }
	   if(x==0){ ch4_flag=0; R_PG_IO_PORT_Write_P73(0);}
	   else if(x==1){ ch3_flag=0; R_PG_IO_PORT_Write_P72(0);}
	   else if(x==2){ ch2_flag=0;  R_PG_IO_PORT_Write_P71(0);}
	   else if(x==3){ ch1_flag=0; R_PG_IO_PORT_Write_P70(0);}
  	   x++; x=x%4;
      }
 
		
		
		
		
		  if(ch1_flag) 
	       {	
		   R_PG_IO_PORT_Write_PA(na[i[0]]);		
		   R_PG_IO_PORT_Write_PB(nb[i[0]]);
		   R_PG_IO_PORT_Write_P7(1);
	  	   for(s=0;s<500;s++);
	       }  
		  
		   if(ch2_flag)
		   { R_PG_IO_PORT_Write_PA(na[i[1]]);  
		     R_PG_IO_PORT_Write_PB(nb[i[1]]);
		     R_PG_IO_PORT_Write_P7(2);
		     for(s=0;s<500;s++);
		   }
		   
		   
		   if(ch3_flag)
		   { R_PG_IO_PORT_Write_PA(na[i[2]]);
		     R_PG_IO_PORT_Write_PB(nb[i[2]]);
		     R_PG_IO_PORT_Write_P7(4);
		     for(s=0;s<500;s++);
		   }
		   
		   if(ch4_flag)
		   {  R_PG_IO_PORT_Write_PA(na[i[3]]);
		      R_PG_IO_PORT_Write_PB(nb[i[3]]);
		      R_PG_IO_PORT_Write_P7(8);
		      for(s=0;s<500;s++);
		  } 
	   
	}

}
void Sci0ReFunc(void)
{

  R_PG_SCI_StartReceiving_C0(&rx,1);
  
  if (rx[0]=='x') back_flag=1;
  
  if(k==1) ch2_flag=1;
  else if (k==2) ch3_flag=1;
  else if (k==3) ch4_flag=1;
 
  if(rx[0] >= '0' && rx[0]<='9' &&!back_flag)
  {  
	  for(s=3;s>0;s--)
      i[s]=i[s-1];
	  
	  for(s=0;s<=9;s++)
	  {
	     if(rx[0] == (48+s)) {
			 i[0]=s;
			 k++;
			 k%=4;
		 }
	  }
	  ch1_flag=1;
	  x=0;
  }	 
  
  if(rx[0]=='c')
  {
	 for(s=0;s<=3;s++) i[s]=0;
	 k=0;x=0;
	 ch1_flag=0;
	 ch2_flag=0;
	 ch3_flag=0;
	 ch4_flag=0;
	  R_PG_IO_PORT_Write_P7(0);	 
  }				 	
  
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
