/***********************************************************************/
/*                                                                     */
/*  FILE        :ADC_CMT_GET_7.c                                       */
/*  DATE        :Thu, Apr 12, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

int num[10]={63,6,91,79,102,109,125,39,127,111},voltage[4]={0,0,0,0},flag=0,j=0;
unsigned int adc_result=0;
float v=0;

void main(void)
{
	R_PG_Clock_Set();
	R_PG_IO_PORT_Set_P7();
	R_PG_IO_PORT_Set_PB();
	R_PG_ADC_12_Set();
	R_PG_ADC_12_Set_S12ADA0();
	R_PG_Timer_Start_CMT_U0_C0();
	R_PG_Timer_Start_CMT_U0_C1();

    R_PG_ADC_12_StartConversionSW_S12ADA0();
	R_PG_ADC_12_GetResult_S12ADA0(&adc_result);
	
	while(1)
	{
		
	   v=(adc_result*5000/4095);
	   voltage[0]=(int)v/1000;
	   voltage[1]=((int)v/100%10);
	   voltage[2]=((int)v/10%10);
	   voltage[3]=((int)v%10);
	  
	
	}

}

 
void Cmt0IntFunc(void) //Åªadc_result ©µ¿ðTimer
{
	if(flag){
		R_PG_ADC_12_StartConversionSW_S12ADA0();
	    R_PG_ADC_12_GetResult_S12ADA0(&adc_result);
		flag=0;
	};
}
 void Cmt1IntFunc(void)  //Channel ©µ¿ðTimer
{
	if(j==0){ 
		R_PG_IO_PORT_Write_PB(num[voltage[3]]);
		R_PG_IO_PORT_Write_P7(1);
	}
	else if(j==1) {
		R_PG_IO_PORT_Write_PB(num[voltage[2]]);
		R_PG_IO_PORT_Write_P7(2);
	}
	else if(j==2) {
		R_PG_IO_PORT_Write_P7(4);
	    R_PG_IO_PORT_Write_PB(num[voltage[1]]);
	}
	else if(j==3) {	
	    R_PG_IO_PORT_Write_PB(num[voltage[0]]+128);
		R_PG_IO_PORT_Write_P7(8);
	}
	
	j++;
	j=j%4;
}
 
void S12ad0IntFunc(void)
{
	flag=1;
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
